# Generated by Django 3.0.4 on 2020-03-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlepost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='likes',
        ),
    ]
